version: '3.8'
services:
  postgresql:
    image: postgres:15-alpine
    container_name: banking-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: banking
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d banking"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking-network

  redis:
    image: "redis:alpine"
    container_name: banking-redis
    ports:
      - "6379:6379"
    networks:
      - banking-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: banking-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_BROKER_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_NODE_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'ci-non-prod-cluster-01'
    networks:
      - banking-network

  zipkin:
    image: openzipkin/zipkin
    container_name: banking-zipkin
    ports:
      - "9411:9411"
    networks:
      - banking-network

  prometheus:
    image: prom/prometheus
    container_name: banking-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - banking-network

  grafana:
    image: grafana/grafana
    container_name: banking-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - banking-network

volumes:
  postgres_data:

networks:
  banking-network:
    driver: bridge
